"""Pack HKO annual Gregorian/lunar tables into 800 bytes for offline RLCD use.

Input: cached T1901e.txt through T2100e.txt, downloaded from
https://www.hko.gov.hk/en/gts/time/calendar/text/files/T{year}e.txt
This maintenance tool does not run during a firmware build.
"""
import argparse
import calendar
import datetime
import hashlib
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
BOARD = ROOT / "main/boards/waveshare/esp32-s3-rlcd-4.2"
LINE = re.compile(r"^(\d{4})/(\d{1,2})/(\d{1,2})\s+(?:(\d+)(?:st|nd|rd|th)?\s+Lunar\s+Month|(\d+))", re.I)


def generate(cache):
    rows = []
    month, lunar_year, previous_day, leap = 11, 1900, 10, False
    previous_date = datetime.date(1900, 12, 31)
    for year in range(1901, 2101):
        count = 0
        for line in (cache / f"T{year}e.txt").read_text(errors="replace").splitlines():
            match = LINE.match(line)
            if not match:
                continue
            y, m, d, new_month, day = match.groups()
            date = datetime.date(int(y), int(m), int(d))
            # The English 2069 text table omits Dec 30, between lunar days 16 and 18.
            # The Chinese T2069c.txt table includes Dec 30 as lunar seventeen.
            # Both adjacent English entries agree; do not extrapolate other gaps.
            if date == datetime.date(2069, 12, 31) and previous_date == datetime.date(2069, 12, 29):
                assert previous_day == 16 and day == "18" and not new_month
                rows.append((datetime.date(2069, 12, 30), lunar_year, month, 17, leap))
                previous_date, previous_day = datetime.date(2069, 12, 30), 17
                count += 1
            assert date == previous_date + datetime.timedelta(days=1), date
            if new_month:
                new_month = int(new_month)
                leap = new_month == month
                assert leap or new_month == month % 12 + 1, date
                month, day = new_month, 1
                assert previous_day in (29, 30), date
                if month == 1 and not leap:
                    lunar_year = year
            else:
                day = int(day)
                assert day == previous_day + 1 and 1 <= day <= 30, date
            rows.append((date, lunar_year, month, day, leap))
            previous_date, previous_day = date, day
            count += 1
        assert count == 365 + calendar.isleap(year), (year, count)

    encoded = []
    for year in range(1901, 2101):
        year_rows = [row for row in rows if row[0].year == year]
        _, _, start_month, start_day, _ = year_rows[0]
        index, leap_index, lengths = 0, 15, 0
        for position, (_, _, _, day, is_leap) in enumerate(year_rows):
            if position and day == 1:
                index += 1
            if is_leap:
                assert leap_index in (15, index), year
                leap_index = index
            if day == 30:
                lengths |= 1 << index
        assert index <= 13
        # Jan 1 month/day and the leap-month index; 15 means no leap month.
        anchor = start_month | (start_day << 4) | (leap_index << 9)
        encoded.append(f"    {{0x{anchor:04x}, 0x{lengths:04x}}},  // {year}")
    header = "// HKO Gregorian/lunar data, 1901-2100. Generated by scripts/generate_rlcd_lunar_data.py.\n"
    header += "// Source: https://www.hko.gov.hk/en/gts/time/conversion1_text.htm\n"
    header += "// Final partial month length is unused: conversion rejects dates after 2100-12-31.\n"
    (BOARD / "dashboard_lunar_data.inc").write_text(header + "\n".join(encoded) + "\n")
    digest = hashlib.sha256()
    for date, ly, lm, ld, is_leap in rows:
        digest.update(f"{date.year},{date.month},{date.day},{ly},{lm},{ld},{int(is_leap)}\n".encode())
    fixture = ROOT / "scripts/tests/fixtures/rlcd_lunar_hko.json"
    fixture.parent.mkdir(exist_ok=True)
    fixture.write_text(json.dumps({
        "source": "https://www.hko.gov.hk/en/gts/time/conversion1_text.htm",
        "range": "1901-01-01 through 2100-12-31",
        "days": len(rows), "sha256": digest.hexdigest(),
    }, indent=2) + "\n")
    print(f"Packed {len(rows)} verified daily records into 800 bytes; SHA256 {digest.hexdigest()}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("cache", type=pathlib.Path)
    generate(parser.parse_args().cache)
